version: '3.8'

services:
  # Serviço 1: O Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine # Usa uma imagem oficial e leve do PostgreSQL
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sua_senha_aqui # IMPORTANTE: Use a mesma senha do seu application.properties
      - POSTGRES_DB=estudo_db
    ports:
      - "5432:5432" # Mapeia a porta do container para a sua máquina (para podermos usar o pgAdmin)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garante que os dados do banco sejam persistentes

  # Serviço 2: A nossa Aplicação Spring Boot
  app:
    image: meu-organizador-api:latest # Usa a imagem que acabamos de construir
    container_name: spring_app
    build: . # Se a imagem não existir, ele a constrói usando o Dockerfile do diretório atual
    depends_on:
      - db # Garante que o container do banco de dados inicie ANTES da aplicação
    ports:
      - "8080:8080" # Mapeia a porta da aplicação para a sua máquina
    environment:
      # AQUI ESTÁ A MÁGICA: Sobrescrevemos as propriedades para a aplicação se conectar ao container 'db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/estudo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sua_senha_aqui # Use a mesma senha acima
      # Outras variáveis de ambiente poderiam ser adicionadas aqui

volumes:
  postgres_data: # Define o volume para persistência dos dados do postgres